export const defaultFeatureFlags = [
    {
        key: 'page.home',
        label: 'Home Page',
        category: 'page',
        route: '/',
        target: 'Home route',
        description: 'Controls whether the landing page is visible to visitors.',
        enabled: true,
    },
    {
        key: 'page.about',
        label: 'About Page',
        category: 'page',
        route: '/about',
        target: 'About route',
        description: 'Controls the About page visibility.',
        enabled: true,
    },
    {
        key: 'page.solutions',
        label: 'Solutions Page',
        category: 'page',
        route: '/solutions',
        target: 'Solutions route',
        description: 'Controls the Solutions page visibility.',
        enabled: true,
    },
    {
        key: 'page.docs',
        label: 'Docs Page',
        category: 'page',
        route: '/docs',
        target: 'Docs route',
        description: 'Controls the documentation page visibility.',
        enabled: true,
    },
    {
        key: 'page.infrastructure',
        label: 'Infrastructure Page',
        category: 'page',
        route: '/infrastructure',
        target: 'Infrastructure route',
        description: 'Controls the Infrastructure page visibility.',
        enabled: true,
    },
    {
        key: 'page.support',
        label: 'Support Page',
        category: 'page',
        route: '/Donate',
        target: 'Support route',
        description: 'Controls the donation/support page visibility.',
        enabled: true,
    },
    {
        key: 'nav.about',
        label: 'About Link',
        category: 'navigation',
        route: '/about',
        target: 'Navbar and footer link',
        description: 'Controls whether the About navigation link is shown.',
        enabled: true,
    },
    {
        key: 'nav.solutions',
        label: 'Solutions Link',
        category: 'navigation',
        route: '/solutions',
        target: 'Navbar and footer link',
        description: 'Controls whether the Solutions navigation link is shown.',
        enabled: true,
    },
    {
        key: 'nav.docs',
        label: 'Docs Link',
        category: 'navigation',
        route: '/docs',
        target: 'Navbar and footer link',
        description: 'Controls whether the Docs navigation link is shown.',
        enabled: true,
    },
    {
        key: 'nav.infrastructure',
        label: 'Infrastructure Link',
        category: 'navigation',
        route: '/infrastructure',
        target: 'Navbar and footer link',
        description: 'Controls whether the Infrastructure navigation link is shown.',
        enabled: true,
    },
    {
        key: 'nav.support',
        label: 'Support Link',
        category: 'navigation',
        route: '/Donate',
        target: 'Navbar and footer link',
        description: 'Controls whether the Support navigation link is shown.',
        enabled: true,
    },
    {
        key: 'content.home.hero',
        label: 'Home Hero',
        category: 'content',
        route: '/',
        target: 'Hero section',
        description: 'Controls the main hero area on the home page.',
        enabled: true,
    },
    {
        key: 'content.home.workflow',
        label: 'Home Workflow',
        category: 'content',
        route: '/',
        target: 'Workflow section',
        description: 'Controls the workflow section on the home page.',
        enabled: true,
    },
    {
        key: 'content.home.platforms',
        label: 'Home Platforms',
        category: 'content',
        route: '/',
        target: 'Platforms section',
        description: 'Controls the platforms section on the home page.',
        enabled: true,
    },
    {
        key: 'content.home.perspectives',
        label: 'Home Perspectives',
        category: 'content',
        route: '/',
        target: 'Perspectives section',
        description: 'Controls the perspectives section on the home page.',
        enabled: true,
    },
    {
        key: 'content.home.skills',
        label: 'Home Skills',
        category: 'content',
        route: '/',
        target: 'Skills section',
        description: 'Controls the skills section on the home page.',
        enabled: true,
    },
    {
        key: 'content.home.cta',
        label: 'Home CTA',
        category: 'content',
        route: '/',
        target: 'Call-to-action section',
        description: 'Controls the CTA section on the home page.',
        enabled: true,
    },
    {
        key: 'content.about.timeline',
        label: 'About Timeline',
        category: 'content',
        route: '/about',
        target: 'Journey timeline',
        description: 'Controls the timeline block inside the About page.',
        enabled: true,
    },
    {
        key: 'content.about.values',
        label: 'About Values',
        category: 'content',
        route: '/about',
        target: 'Values grid',
        description: 'Controls the values block inside the About page.',
        enabled: true,
    },
    {
        key: 'content.solutions.grid',
        label: 'Solutions Grid',
        category: 'content',
        route: '/solutions',
        target: 'Solutions cards',
        description: 'Controls the solutions card grid.',
        enabled: true,
    },
    {
        key: 'content.solutions.process',
        label: 'Solutions Process',
        category: 'content',
        route: '/solutions',
        target: 'Process steps',
        description: 'Controls the process section on the Solutions page.',
        enabled: true,
    },
    {
        key: 'content.infrastructure.hero',
        label: 'Infrastructure Hero',
        category: 'content',
        route: '/infrastructure',
        target: 'Hero section',
        description: 'Controls the hero block on the Infrastructure page.',
        enabled: true,
    },
    {
        key: 'content.infrastructure.stack',
        label: 'Infrastructure Stack',
        category: 'content',
        route: '/infrastructure',
        target: 'Stack preview',
        description: 'Controls the stack preview on the Infrastructure page.',
        enabled: true,
    },
    {
        key: 'content.support.hero',
        label: 'Support Hero',
        category: 'content',
        route: '/Donate',
        target: 'Support experience',
        description: 'Controls the donation/support experience.',
        enabled: true,
    },
    {
        key: 'content.footer.activity',
        label: 'Footer Activity',
        category: 'content',
        route: '/',
        target: 'Footer activity section',
        description: 'Controls the live GitHub and LeetCode activity section in the footer.',
        enabled: true,
    },
    {
        key: 'content.footer.githubActivity',
        label: 'Footer GitHub Activity',
        category: 'content',
        route: '/',
        target: 'GitHub activity card',
        description: 'Controls the GitHub contribution card in the footer.',
        enabled: true,
    },
    {
        key: 'content.footer.leetcodeActivity',
        label: 'Footer LeetCode Activity',
        category: 'content',
        route: '/',
        target: 'LeetCode activity card',
        description: 'Controls the LeetCode activity card in the footer.',
        enabled: true,
    },
];

export const featureFlagSelect = {
    key: 1,
    label: 1,
    category: 1,
    route: 1,
    target: 1,
    description: 1,
    enabled: 1,
    updatedAt: 1,
};